/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS		0x40023800UL

#define RCC_CR_REG_OFFSET		0x00UL

#define RCC_CR_REG_ADDR			(RCC_BASE_ADDRESS + RCC_CR_REG_OFFSET)

int main(void)
{
	uint32_t *pRccCrReg = (uint32_t*)RCC_CR_REG_ADDR;
	printf("Before %s\n", !(*pRccCrReg & (1 << 17)) ? "true" : "false");
	*pRccCrReg |= (1 << 16);
	printf("After %s\n", !(*pRccCrReg & (1 << 17)) ? "true" : "false");
	while ((*pRccCrReg & (1 << 17)) != (1 << 17))
		printf("Loop %s\n", !(*pRccCrReg & (1 << 17)) ? "true" : "false");
	for(;;);
}
